; PlatformIO Project Configuration File para o Traçador I-V e Estação Meteorológica
; Placa: Heltec WiFi LoRa 32 (V2)

[platformio]
default_envs = receptor

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:receptor]
board = heltec_wifi_lora_32_V2
build_src_filter = +<main_receptor.cpp> +<web_dashboard.h> +<web_teste.h> -<main_emissor.cpp>
lib_deps =
    sandeepmistry/LoRa@^0.8.0
    4-20ma/ModbusMaster@^2.0.1
    adafruit/RTClib@^2.1.4
    olikraus/U8g2@^2.36.5
    ESP32Async/ESPAsyncWebServer@^3.7.1
    ESP32Async/AsyncTCP@^3.3.2

[env:emissor]
board = heltec_wifi_lora_32_V2
build_src_filter = +<main_emissor.cpp> -<main_receptor.cpp>
lib_deps =
    sandeepmistry/LoRa@^0.8.0
    heltecautomation/Heltec ESP32 Dev-Boards@^2.0.2
